# Generated by Django 4.2.7 on 2023-12-21 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_title', models.CharField(max_length=100)),
                ('fact_fact', models.TextField()),
                ('fact_consideration', models.TextField()),
                ('fact_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_problem', models.CharField(max_length=200)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post_description', models.TextField()),
                ('post_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
