# Generated by Django 4.2.7 on 2023-12-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_title', models.CharField(max_length=100)),
                ('fact_fact', models.TextField()),
                ('fact_consideration', models.TextField()),
                ('fact_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
