# Generated by Django 4.2.7 on 2023-12-22 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_loggineduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggineduser',
            name='user_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 22, 12, 13, 12, 64609, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
