# Generated by Django 4.2.7 on 2023-12-13 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_content',
            field=models.ImageField(default=datetime.datetime(2023, 12, 13, 14, 24, 7, 78731, tzinfo=datetime.timezone.utc), upload_to=''),
            preserve_default=False,
        ),
    ]
