# Generated by Django 4.2.7 on 2023-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_posts_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_content',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
