# Generated by Django 4.2.7 on 2023-12-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_loggineduser_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggineduser',
            name='user_query',
            field=models.CharField(max_length=200),
        ),
    ]
