# Generated by Django 4.2.7 on 2023-12-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_posts_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_content',
            new_name='post_image',
        ),
    ]
