# Generated by Django 4.2.7 on 2023-12-16 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_posts_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_problem',
            field=models.CharField(default=datetime.datetime(2023, 12, 16, 11, 25, 57, 253337, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
