# Generated by Django 4.2.7 on 2023-12-23 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_loggineduser_user_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_objective', models.TextField()),
                ('total_experience', models.IntegerField()),
                ('current_location', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('martial_status', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('languages', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
