# Generated by Django 4.2.7 on 2023-12-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_aboutme_alter_posts_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='martial_status',
        ),
    ]
