# Generated by Django 4.2.7 on 2023-12-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_aboutme_dob_remove_aboutme_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=30)),
                ('project_description', models.TextField()),
                ('project_link', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
