# Generated by Django 4.2.7 on 2023-12-23 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_projectitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitems',
            name='project_poster',
            field=models.ImageField(default=datetime.datetime(2023, 12, 23, 13, 47, 38, 966727, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
