# Generated by Django 4.2.7 on 2023-12-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_projectitems_project_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aboutMe',
        ),
    ]
