# Generated by Django 4.2.7 on 2023-12-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_delete_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_experience', models.IntegerField()),
                ('current_location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('languages', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=100)),
                ('frameworks', models.CharField(max_length=500)),
                ('versionControl', models.CharField(max_length=200)),
                ('others', models.CharField(max_length=100)),
            ],
        ),
    ]
