# Generated by Django 4.2.7 on 2023-12-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_details_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='personalDetails',
        ),
        migrations.RenameModel(
            old_name='skills',
            new_name='personalSkills',
        ),
    ]
